name: Mistral Common CI

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy_docs:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git credentials 
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.13
      
      - name: Cache env 
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache 
          restore-keys: |
            mkdocs-material-

      - name: Install dependencies
        run: |
          uv sync --all-extras --group docs
          uv pip install -e . --no-deps

      - name: Publish documentation website
        run: mkdocs gh-deploy --force